export const fieldDetailsData = [
  { value: "React", label: "React", color: "blue" },
  { value: "Vue", label: "Vue", color: "green" },
  { value: "Angular", label: "Angular", color: "red" },
  { value: "TypeScript", label: "TypeScript", color: "orange" },
  { value: "Next.js", label: "Next.js", color: "gray" },
  { value: "Flutter", label: "Flutter", color: "green" },
  { value: "Kotlin", label: "Kotlin", color: "red" },
  { value: "Swift", label: "Swift", color: "blue" },
  { value: "Node.js", label: "Node.js", color: "green" },
  { value: "Express", label: "Express", color: "silver" },
  { value: "MySQL", label: "MySQL", color: "orange" },
  { value: "GraphQL", label: "GraphQL", color: "pink" },
  { value: "React Native", label: "React Native", color: "blue" },
  { value: "PostgreSQL", label: "PostgreSQL", color: " navy" },
  { value: "SQLite", label: "SQLite", color: "pale" },
  { value: "Firebase", label: "Firebase", color: "orange" },
  { value: "AWS", label: "AWS", color: "black" },
  { value: "GCP", label: "GCP", color: "red" },
];
