import React from "react";
import { useEffect, useState } from "react";
import Link from "next/link";
import { app, database, storage } from "../../firebaseConfig";
import {
  collection,
  addDoc,
  getDocs,
  doc,
  updateDoc,
  deleteDoc,
  Firestore,
} from "firebase/firestore";
import { useRouter } from "next/router";
import { getAuth, updateProfile, onAuthStateChanged } from "firebase/auth";
import { MuiNavbar } from "../../layouts/MuiNavbar";
import Button from "@mui/material/Button";
import Stack from "@mui/material/Stack";
import Box from "@mui/material/Box";
import TextField from "@mui/material/TextField";
import Card from "@mui/material/Card";
import CardActions from "@mui/material/CardActions";
import CardContent from "@mui/material/CardContent";
import CardMedia from "@mui/material/CardMedia";
import Typography from "@mui/material/Typography";
import Grid from "@material-ui/core/Grid";
import Head from "next/head";
import { ref, uploadBytesResumable, getDownloadURL } from "firebase/storage";

export default function Profile() {
  const [ID, setID] = useState(null);
  const [title, setTitle] = useState("");
  const [context, setContext] = useState("");
  const [file, setFile] = useState("");
  const auth = getAuth();
  const user = auth.currentUser;
  const [photoURL, setPhotoURL] = useState();
  const [displayName, setDisplayName] = useState("");
  let router = useRouter();
  const databaseRef = collection(database, "CRUD DATA");
  const [firedata, setFiredata] = useState([]);
  const [downloadURL, setDownloadURL] = useState(null);
  const [image, setImage] = useState("");
  const [result, setResult] = useState("");
  const [email, setEmail] = useState("");

  console.log(user);
  useEffect(() => {
    let token = sessionStorage.getItem("Token");

    if (token) {
      getData();
    }
    if (!token) {
      router.push("/register");
    }
  }, []);

  useEffect(() => {
    const uploadFile = () => {
      // file && uploadFile;
      const name = new Date().getTime() + file.name;
      const storageRef = ref(storage, file.name);
      const uploadTask = uploadBytesResumable(storageRef, file);

      if (user !== null) {
        user.providerData.forEach((profile) => {
          console.log("Sign-in provider: " + profile.providerId);
          console.log("  Provider-specific UID: " + profile.uid);
          console.log("  Name: " + profile.displayName);
          console.log("  Email: " + profile.email);
          console.log("  Photo URL: " + profile.photoURL);
        });
      }

      uploadTask.on(
        "state_changed",
        (snapshot) => {
          const progress =
            (snapshot.bytesTransferred / snapshot.totalBytes) * 100;
          console.log("Upload is " + progress + "% done");
          switch (snapshot.state) {
            case "paused":
              console.log("Upload is paused");
              break;
            case "running":
              console.log("Upload is running");
              break;
          }
        },
        (error) => {
          console.log(error);
        },
        () => {
          // Handle successful uploads on complete
          // For instance, get the download URL: https://firebasestorage.googleapis.com/...
          getDownloadURL(uploadTask.snapshot.ref).then((downloadURL) => {
            console.log("File available at", downloadURL);
          });
        }
      );
    };
    file && uploadFile();
  }, [file]);

  const getData = async () => {
    await getDocs(databaseRef).then((response) => {
      setFiredata(
        response.docs.map((data) => {
          return { ...data.data(), id: data.id };
        })
        // .filter((data) => (data.data.email == user.email ? data : "none"))
      );
    });
  };

  const getID = (
    id,
    name,
    age,
    title,
    context,
    downloadURL,
    categori,
    cratetime
  ) => {
    setID(id);
    setContext(context);
    setTitle(title);
    setName(name);
    setAge(age);
    setDownloadURL(downloadURL);
    setIsUpdate(true);
    setCategori(categori);
    setCreatetime(cratetime);
  };

  onAuthStateChanged(auth, (user) => {
    if (user) {
      updateProfile({
        displayName: displayName,
        // setPhotoURL: photoURL,
      })
        .then(() => {
          setDisplayName("");
          // setPhotoURL("");
        })
        .catch((error) => {
          console.error(error);
        });
    }
  });

  return (
    <div>
      <Head>
        <title>漫画考察.net</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MuiNavbar />
      <div className="max-w-7xl m-auto">
        <h2 className="m-5 my-12 text-center text-2xl font-semibold">
          プロフィール
        </h2>
        <p className="m-5">ユーザー画像{user && <img src={user.photoURL} />}</p>
        <p className="m-5">名前： {user && <span>{user.displayName}</span>}</p>
        {/* <p className="m-5">自己紹介：</p> */}
        <p className="m-5">
          メールアドレス： {user && <span>{user.email}</span>}
        </p>

        <p className="m-5">過去の投稿</p>

        <Grid container spacing={3}>
          {firedata.map((data) => {
            return (
              <Grid item xs={4} key={data.id} className="">
                <Card sx={{ maxWidth: 400 }} className="">
                  <CardMedia
                    component="img"
                    // height="140"
                    className="w-100 h-100"
                    image={data.downloadURL}
                    alt=""
                  />
                  {/* <img src={data.downloadURL} /> */}
                  <CardContent>
                    <Typography gutterBottom variant="h5" component="div">
                      {data.title}
                    </Typography>
                    <Typography variant="body2" color="text.secondary">
                      <p className="bg-blue-500 p-2 inline-block text-white text-center">
                        {data.categori}
                      </p>
                      <br></br>
                      {data.context}
                      <br></br>
                      {data.name}
                      <br></br>
                      {data.createtime}
                      {data.email}
                    </Typography>
                  </CardContent>
                  {user.email == data.email && (
                    <CardActions>
                      <Button
                        variant="outlined"
                        onClick={() =>
                          getID(
                            data.id,
                            data.name,
                            data.age,
                            data.title,
                            data.context
                          )
                        }
                      >
                        更新する
                      </Button>
                      <Button
                        variant="outlined"
                        onClick={() => deleteDocument(data.id)}
                      >
                        削除する
                      </Button>
                    </CardActions>
                  )}
                </Card>
              </Grid>
            );
          })}
        </Grid>

        <p className="m-5">いいねした投稿：</p>

        <Box
          component="form"
          sx={{
            "& > :not(style)": { m: 1, width: "25ch" },
          }}
          noValidate
          autoComplete="off"
        >
          <TextField
            id="outlined-basic"
            label="名前"
            variant="outlined"
            value={displayName || ""}
            onChange={(event) => setDisplayName(event.target.value)}
          />

          {/* <input type="file"></input> */}
        </Box>

        <Button variant="outlined" className="m-5" onClick={updateProfile}>
          更新する
        </Button>

        <Button variant="outlined" className="m-5" href="">
          <Link href="/profile/edit">更新</Link>
        </Button>
        {/* <Button variant="outlined" className="m-5" href="/profile/edit">
          メールアドレスを変更する
        </Button>
        <Button variant="outlined" className="m-5" href="/profile/edit">
          パスワードを変更する
        </Button> */}
      </div>
    </div>
  );
}
