import React from "react";
import { useEffect, useState } from "react";
import Link from "next/link";
import { app, database, storage } from "../../firebaseConfig";
import {
  collection,
  addDoc,
  getDocs,
  doc,
  updateDoc,
  deleteDoc,
  Firestore,
} from "firebase/firestore";
import { useRouter } from "next/router";
import { getAuth, updateProfile, deleteUser } from "firebase/auth";
import { MuiNavbar } from "../../layouts/components/MuiNavbar";
import Button from "@mui/material/Button";
import Box from "@mui/material/Box";
import TextField from "@mui/material/TextField";
import Card from "@mui/material/Card";
import CardActions from "@mui/material/CardActions";
import CardContent from "@mui/material/CardContent";
import CardMedia from "@mui/material/CardMedia";
import { postImage } from "../api/upload";
import Typography from "@mui/material/Typography";
import Grid from "@material-ui/core/Grid";
import Head from "next/head";
import Image from "react-image-resizer";
import { ref, uploadBytesResumable, getDownloadURL } from "firebase/storage";

export default function Profile() {
  const [ID, setID] = useState(null);
  const [title, setTitle] = useState("");
  const [context, setContext] = useState("");
  const [file, setFile] = useState("");
  const [categori, setCategori] = useState("");
  const auth = getAuth();
  const user = auth.currentUser;
  const [photoURL, setPhotoURL] = useState();
  const [displayName, setDisplayName] = useState("");
  let router = useRouter();
  const [createtime, setCreatetime] = useState("");
  const [isUpdate, setIsUpdate] = useState(false);
  const databaseRef = collection(database, "CRUD DATA");
  const [createObjectURL, setCreateObjectURL] = useState(null);
  const [firedata, setFiredata] = useState([]);
  const [downloadURL, setDownloadURL] = useState(null);
  const [image, setImage] = useState("");
  const [result, setResult] = useState("");
  const [email, setEmail] = useState("");
  const [userid, setUserid] = useState(null);
  const [netabare, setNetabare] = useState("");
  const [opentext, setOpentext] = useState(false);
  const styles = { whiteSpace: "pre-line" };

  console.log(user);
  useEffect(() => {
    let token = sessionStorage.getItem("Token");

    if (token) {
      getData();
    }
    if (!token) {
      router.push("/register");
    }
  }, []);

  // useEffect(() => {
  //   if (user.photoURL == null) {
  //     updateProfile(auth.currentUser, {
  //       photoURL:
  //         "https://firebasestorage.googleapis.com/v0/b/next-auth-app-2aa40.appspot.com/o/images%2F0oglm23o.jpg?alt=media&token=a5d8cdcd-ceca-4852-ba3c-0ca40308a4b8",
  //     })
  //       .then(() => {
  //         setPhotoURL("");
  //         getData();
  //       })
  //       .catch((error) => {
  //         console.error(error);
  //       });
  //   } else {
  //   }
  // }, []);

  const uploadToClient = (event) => {
    if (event.target.files && event.target.files[0]) {
      const file = event.target.files[0];

      setImage(file);
      setCreateObjectURL(URL.createObjectURL(file));
    }
  };

  const updatename = async () => {
    const result = await postImage(image);
    setResult(result);

    updateProfile(auth.currentUser, {
      displayName: displayName,
      // photoURL: result,
    })
      .then(() => {
        alert("プロフィールを更新しました。");
        setDisplayName("");
        setResult("");
        getData();
        router.push("/profile");
      })
      .catch((error) => {
        console.error(error);
      });
  };

  const getData = async () => {
    await getDocs(databaseRef).then((response) => {
      setFiredata(
        response.docs.map((data) => {
          return { ...data.data(), id: data.id };
        })
        // .filter((data) => (data.data.email == user.email ? data : "none"))
      );
    });
  };

  const getID = (
    id,
    title,
    context,
    downloadURL,
    categori,
    cratetime,
    displayname
  ) => {
    setID(id);
    setContext(context);
    setTitle(title);
    setDownloadURL(downloadURL);
    setIsUpdate(true);
    setCategori(categori);
    setCreatetime(cratetime);
    setDisplayName(displayname);
  };

  // onAuthStateChanged(auth, (user) => {
  //   if (user) {
  //     updateProfile({
  //       displayName: displayName,
  //       // setPhotoURL: photoURL,
  //     })
  //       .then(() => {
  //         setDisplayName("");
  //         // setPhotoURL("");
  //       })
  //       .catch((error) => {
  //         console.error(error);
  //       });
  //   }
  // });

  const deleteuser = async () => {
    if (user) {
      deleteUser(user)
        .then(() => {
          sessionStorage.removeItem("Token");
          alert("退会しました。TOP画面に戻ります。");
          router.push("/");
        })
        .catch((error) => {
          console.log(error);
        });
    }
  };

  return (
    <div>
      <Head>
        <title>漫画考察.net</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MuiNavbar />
      <div className="max-w-7xl m-auto">
        <h2 className="m-5 my-12 text-center text-2xl font-semibold">
          プロフィール
        </h2>
        <p className="m-5">
          ユーザー画像
          {user && (
            <Image
              className="m-auto text-center max-w-sm"
              height={100}
              width={100}
              src={user.photoURL}
            />
          )}
        </p>
        <p className="m-5">名前： {user && <span>{user.displayName}</span>}</p>
        {/* <p className="m-5">自己紹介：</p> */}
        <p className="m-5">
          メールアドレス： {user && <span>{user.email}</span>}
        </p>

        <p className="m-5">過去の投稿</p>
        {/* <p className="text-1xl text-center">投稿数　  {data.email == user.email && (<p>{firedata.length}</p>)}件</p> */}

        <Grid container spacing={1}>
          {firedata.map((data) => {
            return (
              <Grid key={data.id} className="flex m-auto">
                {data.email == user.email && (
                  <Card className="lg:w-full w-4/5 my-4">
                    <p className="m-auto text-center">
                      <Image
                        className="m-auto text-center max-w-sm"
                        height={300}
                        width={300}
                        src={data.downloadURL}
                      />
                    </p>
                    <CardContent>
                      <Typography gutterBottom variant="h5" component="div">
                        {data.title}
                      </Typography>
                      <Typography variant="body2" color="text.secondary">
                        {data.categori == "ONE PIECE" && (
                          <p className="bg-blue-500 p-2 inline-block text-white text-center">
                            {data.categori}
                          </p>
                        )}
                        {data.categori == "呪術廻戦" && (
                          <p className="bg-purple-500 p-2 inline-block text-white text-center">
                            {data.categori}
                          </p>
                        )}
                        {data.categori == "東京リベンジャーズ" && (
                          <p className="bg-rose-500 p-2 inline-block text-white text-center">
                            {data.categori}
                          </p>
                        )}
                        {data.categori == "キングダム" && (
                          <p className="bg-yellow-500 p-2 inline-block text-white text-center">
                            {data.categori}
                          </p>
                        )}
                        <br></br>
                        <br></br>
                        <div className="w-80 m-auto">{data.context}</div>
                        <br></br>
                        {data.name}
                        <br></br>
                        {data.createtime}
                      </Typography>
                    </CardContent>
                    {/* {user.email == data.email && (
                      <CardActions>
                        <Button
                          variant="outlined"
                          onClick={() =>
                            getID(
                              data.id,
                              data.name,
                              data.age,
                              data.title,
                              data.context
                            )
                          }
                        >
                          更新する
                        </Button>
                        <Button
                          variant="outlined"
                          onClick={() => deleteDocument(data.id)}
                        >
                          削除する
                        </Button>
                      </CardActions>
                    )} */}
                  </Card>
                )}
              </Grid>
            );
          })}
        </Grid>

        {/* <p className="m-5">いいねした投稿：</p> */}

        <Box
          component="form"
          sx={{
            "& > :not(style)": { m: 1, width: "25ch" },
          }}
          noValidate
          autoComplete="off"
        >
          <p>名前の更新</p>

          <TextField
            id="outlined-basic"
            label="名前"
            variant="outlined"
            // value={displayName}
            onChange={(event) => setDisplayName(event.target.value)}
          />
          <br></br>
          {/* <img
            className="flex justify-center items-center m-auto  w-full"
            src={createObjectURL}
          />
          <label
            htmlFor="file-input"
            className="bg-primary-900 text-white-900 dark:bg-dark-900 flex justify-center items-center px-4 py-2 rounded mb-6 w-full"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="h-10 w-10 hover:cursor-pointer hover:bg-gray-700"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
              strokeWidth="2"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"
              />
            </svg>
          </label>
          <input
            id="file-input"
            className="hidden"
            type="file"
            accept="image/*"
            name="myImage"
            onChange={uploadToClient}
          /> */}
        </Box>
        <br></br>
        <Button variant="outlined" className="m-5" onClick={updatename}>
          名前を更新する
        </Button>
        {/* <Button variant="outlined" className="m-5">
          <Link href="/profile/emailedit">メールアドレスを変更する</Link>
        </Button> */}
        <br></br>
        <br></br>
        <Button variant="outlined" className="m-5">
          <Link href="/profile/passwordedit">パスワードを変更する</Link>
        </Button>
        <br></br>
        <br></br>
        <Button variant="outlined" className="m-5">
          <Link href="/profile/photoedit"> プロフィール画像を更新する</Link>
        </Button>
        <br></br>
        <br></br>
        <Button variant="outlined" className="m-5" onClick={deleteuser}>
          アカウントを退会する
        </Button>
      </div>
    </div>
  );
}
