import { MuiNavbar } from "layouts/components/MuiNavbar";
import Head from "next/head";

export default function Custom404() {
  return (
    <>
      <Head>
        <title>漫画考察.net/記事投稿</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MuiNavbar />
      <h1 className="text-center m-10">ページが見つかりませんでした</h1>
    </>
  );
}
