import React from "react";
import { MuiNavbar } from "../packages/components/MuiNavbar";
import Head from "next/head";

function Contact() {
  return (
    <div>
      <Head>
        <title>漫画考察.net/About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MuiNavbar />
      <div className="max-w-7xl m-auto">
        <h2 className="m-5 my-12 text-center text-2xl font-semibold">About</h2>
        <p className="">お問合せ</p>
        <br></br>
      </div>
    </div>
  );
}

export default Contact;
