import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { app } from "../firebaseConfig";
import Button from "@mui/material/Button";
import * as React from "react";
import Stack from "@mui/material/Stack";
import { MuiNavbar } from "../layouts/MuiNavbar";

export default function aaa() {
  <Head>
    <link
      href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@500&display=swap"
      rel="stylesheet"
    />
  </Head>;
  return (
    <div className={styles.container}>
      <Head>
        <title>漫画考察.net</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MuiNavbar />
      <div className="max-w-7xl m-auto">
        <main className={styles.main}>
          <br></br>
          <br></br>
          <h2 className="m-5 text-2xl font-semibold">漫画考察.net</h2>
          <p className="m-5">
            漫画考察.netでは、漫画の考察などを自由に投稿・閲覧できるwebサイトです。
          </p>
          <br></br>
          <Stack spacing={2} direction="row" className="m-5">
            <Button variant="outlined">
              <Link href="/register">新規登録はこちら</Link>
            </Button>
            <Link href="/login">
              <Button variant="outlined">ログインはこちら</Button>
            </Link>
          </Stack>
        </main>
      </div>
    </div>
  );
}
